# Generated by Django 3.0.8 on 2020-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getdate', models.DateField()),
                ('booktype', models.CharField(max_length=200)),
                ('booktitle', models.TextField()),
            ],
        ),
    ]
